todo/todo/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todoapp/',include('todoapp.urls',namespace='todoapp')),
]

todo/todoapp/urls.py
from django.urls import path
from . import views

app_name = 'todoapp'

urlpatterns = [
    path('',views.index,name='index'),
    path('addtodo/',views.addtodo,name='addtodo'),
    path('deleteitem/<int:id>/',views.deleteitem,name='deleteitem'),
]

todo/todoapp/models.py
from django.db import models

# Create your models here.

class TodoItem(models.Model):
    todo_item = models.CharField(max_length=50,verbose_name="事件")
    todo_date = models.DateTimeField(auto_now_add=True,verbose_name="时间")

    class Meta:
        verbose_name = "简单的记事本"
        verbose_name_plural = "简单的记事本"
        ordering = ["-todo_date"]

todo/todoapp/views.py
from django.shortcuts import render
#from django.http import HttpResponse
from django.http import HttpResponseRedirect
from .models import TodoItem

# Create your views here.

def index(request):
    objs = TodoItem.objects.all()
    context = {'objs':objs}
    return render(request,'index.html',context=context)

def addtodo(request):
    c = request.POST['content']
    new_obj = TodoItem(todo_item = c)
    new_obj.save()
    return HttpResponseRedirect("/todoapp/")

def deleteitem(request,id):
    obj = TodoItem.objects.get(pk=id)
    obj.delete()
    return HttpResponseRedirect("/todoapp/")

todo/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>这是一个简单的记事本</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
        <div class="container">
            <h1 style="color:red">你好呀！</h1>
            <br>
            <br>
            {% for obj in objs %}
            <div class="card">
                <div class='card-body'>
                    <h2 class="card-title">{{ obj.todo_item }}</h2>
                </div>
                <div class='card-text'>
                    <form action="{% url 'todoapp:deleteitem' obj.id %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="Delete">
                    </form>
                </div>
                <div class="card-footer">
                    Posted on {{ obj.todo_date }}
                </div>
            </div>
            <br>
            {% endfor %}
            <br>
            <form action="{% url 'todoapp:addtodo' %}" method="post">
                {% csrf_token %}
                <input type="text" name="content">
                <input type="submit" value="Add todoItem">
            </form>
            <br>
            <h1 style="color:chocolate">你好呀！</h1>
        </div>
    </body>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</html>