blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('entries/',include('entries.urls',namespace='entries')),
    path('users/',include('users.urls',namespace='users')),
]

blog/entries/urls.py
from django.urls import path
from . import views

app_name = 'entries'

urlpatterns = [
    path('',views.HomeView.as_view(),name='blog-home'),
    path('detail/<int:pk>/',views.EntryView.as_view(),name="entry-detail"),
    path('create_entry/',views.CreateEntryView.as_view(success_url='/entries/'),name='create_entry'),
]

blog/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),
         name='logout'),
]

blog/entries/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Entry(models.Model):
    entry_title = models.CharField(max_length=50)
    entry_text = models.TextField()
    entry_date = models.DateTimeField(auto_now_add=True)
    entry_author = models.ForeignKey(User,on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.entry_title

blog/entries/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Entry

# Create your views here.

#def index(request):
    #return render(request,'entries/index.html')

class HomeView(LoginRequiredMixin,ListView):
    model = Entry
    template_name = 'entries/index.html'
    context_object_name = "blogentries"
    ordering = ['-entry_date']
    paginate_by = 2

class EntryView(LoginRequiredMixin,DetailView):
    model = Entry
    template_name = 'entries/entry_detail.html'

class CreateEntryView(LoginRequiredMixin,CreateView):
    model = Entry
    template_name = 'entries/create_entry.html'
    fields = ['entry_title','entry_text']

    def form_valid(self, form):
        form.instance.entry_author = self.request.user
        return super().form_valid(form)

blog/users/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .form import RegistrationForm
from django.contrib.auth import authenticate, login

# Create your views here.
def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = request.POST['username']
            password = request.POST['password1']
            user = authenticate(request,username=username,password=password)
            login(request,user)
            return redirect('entries:blog-home')
    else:
        form = RegistrationForm()

    context = {'form':form}
    return render(request,'users/register.html',context=context)

blog/templates/entries/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="{% static 'entries/css/blog-home.css' %}" rel="stylesheet">

</head>
<body>
{% include 'entries/header.html'%}
{% block content %}{% endblock %}
{% include 'entries/footer.html' %}
</body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</html>

blog/templates/entries/create_entry.html
{% extends 'entries/base.html' %}

{% load staticfiles %}

{% block title%}Blog Home Page {% endblock %}

{% block content%}


  <!-- Page Content -->
  <div class="container">

    <div class="row">
      <div class="col-md-8">
        <br>
        <br>
        <br>
        <br>
        <a href="{% url 'entries:blog-home' %}" style="font-size:40px;">Back to Home</a>
        <br>
        <br>
        <div class="card mb-4">
          <div class="card-header">
              Create Blog Post
          </div>
          <div class="card-body">
              <form method="POST">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button type="submit" class="btn btn-primary">Post Entry</button>
              </form>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

blog/templates/entries/entry_detail.html
{% extends 'entries/base.html' %}

{% load staticfiles %}

{% block title%}Blog Home Page {% endblock %}

{% block content%}


  <!-- Page Content -->
  <div class="container">

    <div class="row">
      <div class="col-md-8">
        <br>
        <br>
        <br>
        <br>
        <a href="{% url 'entries:blog-home' %}" style="font-size:40px;">Back to Home</a>
        <br>
        <br>
        <div class="card mb-4">
          <div class="card-body">
            <h2 class="card-title">{{ object.entry_title  }}</h2>
            <p class="card-text">{{ object.entry_text  }}</p>

          </div>
          <div class="card-footer text-muted">
            Posted os {{ object.entry_date }}
            <a >{{ object.entry_author }}</a>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

blog/templates/entries/footer.html
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->

blog/templates/entries/header.html
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Start Bootstrap</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

blog/templates/entries/index.html
{% extends 'entries/base.html' %}

{% load staticfiles %}

{% block title%}Blog Home Page {% endblock %}

{% block content%}


  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">
        <br>
        <br>
        <br>
        <h1 class="my-4">
          <a href="{% url 'entries:create_entry' %}">Create Blog</a>
          <small><a href="{% url 'users:register' %}">Create Account</a></small>
          <a href="{% url 'users:login' %}">Login</a>
          <a href="{% url 'users:logout' %}">Logout</a>
        </h1>

        <!-- Blog Post -->
        {% for entry in blogentries %}
        <div class="card mb-4">
          <div class="card-body">
            <h2 class="card-title">{{ entry.entry_title  }}</h2>
            <p class="card-text">{{ entry.entry_text | truncatechars:100 }}</p>
            <a href="{% url 'entries:entry-detail' entry.pk %}" class="btn btn-primary">Read More &rarr;</a>
          </div>
          <div class="card-footer text-muted">
            {{ entry.entry_date }}
            <a href="#">{{ entry.entry_author }}</a>
          </div>
        </div>
        {% endfor %}



        <!-- Pagination -->
        {% if is_paginated %}
        <ul class="pagination justify-content-center mb-4">
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous age</a>
          </li>
          {% endif %}

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next Page</a>
          </li>
          {% endif %}
        </ul>
        {% endif %}

      </div>

      <!-- Sidebar Widgets Column -->

      <div class="col-md-4">
        <br>
      <br>
      <br>
      <br>
      <br>


        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>


        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Login Information</h5>
          <div class="card-body">
            <p><strong>Username:</strong> {{ user.username }}</p>
            <p><strong>Useremail:</strong> {{ user.email }}</p>
          </div>
        </div>

      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->

{% endblock %}

blog/templates/users/login.html
{% extends 'entries/base.html' %}

{% load staticfiles %}

{% block title%}Blog Home Page {% endblock %}

{% block content%}


  <!-- Page Content -->
  <div class="container">

    <div class="row">
      <div class="col-md-8">
        <br>
        <br>
        <br>
        <br>
        <a href="{% url 'entries:blog-home' %}" style="font-size:40px;">Back to Home</a>
        <br>
        <br>
        <div class="card mb-4">
          <div class="card-header">
              Login to your Account
          </div>
          <div class="card-body">
              <form method="POST">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button type="submit" class="btn btn-primary">Log in</button>
              </form>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

blog/templates/users/logout.html
{% extends 'entries/base.html' %}

{% load staticfiles %}

{% block title%}Blog Home Page {% endblock %}

{% block content%}


  <!-- Page Content -->
  <div class="container">

    <div class="row">
      <div class="col-md-8">
        <br>
        <br>
        <br>
        <br>
          <h1>You have successfully logged out.</h1>
        <a href="{% url 'entries:blog-home' %}" style="font-size:40px;">Back to Home</a>
        <br>
        <br>
      </div>
    </div>
  </div>

{% endblock %}

blog/templates/users/register.html
{% extends 'entries/base.html' %}

{% load staticfiles %}

{% block title%}Blog Home Page {% endblock %}

{% block content%}


  <!-- Page Content -->
  <div class="container">

    <div class="row">
      <div class="col-md-12">
        <br>
        <br>
        <br>
        <br>
        <a href="{% url 'entries:blog-home' %}" style="font-size:40px;">Back to Home</a>
        <br>
        <br>
        <div class="card mb-4">
          <div class="card-header">
              Create An Account
          </div>
          <div class="card-body">
              <form method="POST">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button type="submit" class="btn btn-primary">Create Account</button>
              </form>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}