YoutubeVideoDownloader/YoutubeVideoDownloader/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('youtube_download/',include('youtube_download.urls',namespace='youtube_download')),
]

YoutubeVideoDownloader/youtube_download/urls.py
from django.urls import path
from . import views

app_name = 'youtube_download'

urlpatterns = [
    path('',views.index,name='index'),
    path('ytb_main/',views.ytb_main,name='ytb_main'),
    path('ytb_download/',views.ytb_download,name='ytb_download'),
    path('download_complete/<res>',views.download_complete,name='download_complete'),
]

YoutubeVideoDownloader/youtube_download/views.py
from django.shortcuts import render
from django.shortcuts import redirect

import os
from pytube import YouTube

# Create your views here.

def index(request):
    return render(request,'index.html')

def ytb_main(request):
    return render(request,'ytb_main.html')

def ytb_download(request):
    global url
    url = request.GET.get('url')
    print(url)
    try:
        obj = YouTube(url)
        resolutions = []
        strm_all = obj.streams.filter(progressive=True,file_extension='mp4').all()
        for i in strm_all:
            resolutions.append(i.resolution)
        print(resolutions)
        resolutions = list(dict.fromkeys(resolutions))
        embed_link = url.replace("watch?v=","embed/")
        context = {
            'rsl':resolutions,
            'embed_link':embed_link,
        }
        return render(request,'ytb_download.html',context=context)
    except:
        return render(request,'sorry.html')


def download_complete(request,res):
    global url
    print(res)
    homedir = os.path.expanduser("~")
    dirs = homedir + "/Downloads"
    print(homedir)
    print(f'DIRECT:',f'{dirs}/Downloads')
    if request.method == "POST":
        YouTube(url).streams.get_by_resolution(res).download(dirs)
        return render(request,'download_complete.html')
    else:
        return redirect("youtube_download:ytb_main")

YoutubeVideoDownloader/youtube_download/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</head>

<body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</body>
</html>

YoutubeVideoDownloader/youtube_download/templates/download_complete.html
{% extends 'base.html' %}

{% block title %}下载结果{% endblock %}

{% block content %}

<div class="container">
    <br>
    <h1 style="background-color: chartreuse;">下载成功</h1>
    <h1 style="background-color: chocolate;"><a href="{% url 'youtube_download:ytb_main' %}">返回主页</a></h1>
</div>

{% endblock %}

YoutubeVideoDownloader/youtube_download/templates/index.html
<h1>你好吗？</h1>

YoutubeVideoDownloader/youtube_download/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
    <a class="navbar-brand" href="#">Download video from youtube</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
    </div>
</nav>

YoutubeVideoDownloader/youtube_download/templates/sorry.html
<h1>骚凹瑞</h1>
<h1><a href="{% url 'youtube_download:ytb_main' %}">Return Homepage</a></h1>

YoutubeVideoDownloader/youtube_download/templates/ytb_download.html
{% extends 'base.html' %}

{% block title %}下载{% endblock %}

{% block content %}

<div class="container">
    <br>
    <center><h1>Your video</h1></center>
    <br>
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src={{ embed_link }} allowfullscreen></iframe>
      </div>
    <br><br>
    <table class="table">
        <thead class="thead-dark">
          <tr>
            <th>Select resolution</th>
            <th>Download</th>
          </tr>
        </thead>
        {% for i in rsl %}
        <tbody>
          <tr>
            <td>{{ i }}</td>
            <td>
                <form action="{% url 'youtube_download:download_complete' i %}" method="POST" class="post-form">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger" value="DOWNLOAD">Download</button>
                </form>
            </td>
          </tr>
        </tbody>
        {% endfor %}
    </table>
</div>

{% endblock %}

YoutubeVideoDownloader/youtube_download/templates/ytb_main.html
{% extends 'base.html' %}

{% block title %} 首页 {% endblock %}

{% block content %}

<div class="container">
    <br><br>
    <center><h1>Enter youtube video link Here</h1></center>
    <br>
    <form action="{% url 'youtube_download:ytb_download' %}" method="GET">
        <div class="form-group">
            <label>Enter Link</label>
            <input name="url" type="text" class="form-control" id="link" aria-describedby="emailHelp" placeholder="Entre Your Selected Youtube Video Link">
        </div>
    <br>
    <center>
        <button type="submit" class="btn btn-primary">Submit</button>
    </center>
    </form>
</div>

{% endblock %}