myproj/extractseq/urls.py
from django.urls import path
from . import views

app_name = 'extractseq'

urlpatterns = [
    path('',views.index,name='index'),
    path('extractseq/',views.extractseq,name='extractseq'),
]

myproj/myproj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('extractseq/',include('extractseq.urls',namespace='extraceseq')),
]

myproj/extractseq/models.py
from django.db import models

# Create your models here.

myproj/extractseq/forms.py
from django import forms

class ExtractseqForm(forms.Form):
    sequences = forms.CharField(
        label="Paste your sequences here",
        max_length=20000,
        widget=forms.Textarea(
            attrs={
                'class':'form-control',
                'placeholder':">Seq1\nATCGA\n>Seq2\nATGCCA",
            }
        )
    )
    seqids = forms.CharField(
        label="Paste your seq id here",
        max_length=20000,
        widget=forms.Textarea(
            attrs={
                'class':'form-control',
                'placeholder':"Seq1\nSeq2\n",
            }
        )
    )
    filename = forms.CharField(
        label="input the name of output file",
        max_length=200,
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'placeholder':'output.fasta',
            }
        )
    )

myproj/extractseq/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse

from .forms import ExtractseqForm

from .extseqs import extseqs

# Create your views here.

def index(request):
    form = ExtractseqForm()
    context = {
        'form':form
    }
    return render(request,'extractseq/index.html',context=context)

def extractseq(request):
    if request.method == "POST":
        sequences = request.POST['sequences']
        seqids = request.POST['seqids']
        outfile = request.POST['filename']
        print(seqids)
        output_seq = extseqs(sequences,seqids)
        print(output_seq)
        response_content = ''.join(output_seq)
        print(response_content)
        response = HttpResponse(response_content,content_type="text/plain,chartset=utf8")
        response['Content-Disposition'] = 'attachment;filename={}'.format(outfile)
        return response

        #return HttpResponse('<h1>OK</h1>')

myproj/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

myproj/templates/extractseq/index.html
{% extends 'base.html' %}

{% block title %}
首页
{% endblock %}

{% block content %}

<br>
<h1>你好吗？</h1>
<hr>
<br>
<form method="POST" action="{% url 'extractseq:extractseq' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" style="margin: 2rem auto;">
</form>


{% endblock %}